name: saberion_assessment
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^2.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  get_it: ^7.6.7
  connectivity_plus: ^6.0.1
  internet_connection_checker: ^1.0.0+1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  build_verify: ^3.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
